#!/bin/bash

dldir=$OPENSHIFT_DATA_DIR
tcversion="7.0.34"
tcdir="apache-tomcat-$tcversion"
zfile="${tcdir}.tar.gz"


function is_tomcat7_installed() {
   [ -d "$dldir/$tcdir" ]  &&  return 0
   return 1

}  #  End of function  is_tomcat7_installed.


function create_server_xml_template() {
   serverxml="$dldir/$tcdir/conf/server.xml"
   [ -f "${serverxml}.template" ]  ||  cp -p $serverxml ${serverxml}.template

}  #  End of function  create_server_xml_template.


function install_tomcat7() {
   is_tomcat7_installed  &&  return 0

   tcmirror="http://www.us.apache.org/dist/tomcat/"
   zlink="$tcmirror/tomcat-7/v${tcversion}/bin/$zfile"

   if ! curl -L -o "$dldir/$zfile" "$zlink"; then
      echo " - ERROR -- download failed for $zlink"
      echo " - download uri = $dldir/$zfile"
      return 1
   fi

   (cd "$dldir"; tar -zxf "$dldir/$zfile")
   echo " - Done extracting Tomcat version $tcversion"

   create_server_xml_template
   echo " - Done creating Tomcat $tcversion server.xml template"

}  #  End of function  install_tomcat7.


function _setup_server_xml() {
   ip=$OPENSHIFT_INTERNAL_IP
   dns=$OPENSHIFT_APP_DNS

   serverxml="$dldir/$tcdir/conf/server.xml"
   cat "${serverxml}.template" |   \
      sed "s#<Server\s*port=\(\"8005\"\)\(.*\)#<Server address=\"$ip\" port=\"18005\" \2#g;   \
      s#<Connector\s*port=\(\"8080\"\)\(.*\)#<Connector address=\"$ip\" port=\"8080\" \2#g;  \
      s#<Connector\s*port=\(\"8009\"\)\(.*\)#<Connector address=\"$ip\" port=\"18009\" \2#g;  \
           s#redirectPort=\"8443\"#redirectPort=\"18443\"#g;    \
           s#\(defaultHost\|name\)=\"localhost\"#\1=\"$dns\"#g;"  \
         >  "${serverxml}"

   echo " - Done setting up Tomcat $tcversion server.xml configuration"

}  #  End of function  _setup_server_xml.


function start_tomcat7() {
   _setup_server_xml
   #  Run Tomcat w/ a heap size that fits in 512mb gears.
   (export _JAVA_OPTIONS=-Xmx256m; sh $dldir/$tcdir/bin/startup.sh)

}  #  End of function  start_tomcat7.


function stop_tomcat7() {
   sh $dldir/$tcdir/bin/shutdown.sh 

}  #  End of function  stop_tomcat7.

